version: '3'
services:
    young-astrologer-service:
      build: 
        context: .
      port:
          - "8080:8080"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "astrologer123"
        POSTGRES_DB: "postgres"
        APOD_API_KEY: "api.nasa.gov"
      depends_on:
        - postgres

      postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "astrologer123"
          POSTGRES_DB: "postgres"